import { mkdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import {
  renderChangeReportMarkdown,
  renderContractReportMarkdown,
  type AiProvider,
  type ChangeReport,
  type ContractReport,
  type VerifiedChangeReport,
} from "@api-tacet/core";
import { TacetWorkspace } from "./workspace.js";

export type ImpactFailOn = "definite" | "likely" | "possible" | "never";
export type CheckFailOn = "error" | "warning" | "never";
export type VerifyFailOn = "fail" | "warning" | "never";

export interface CiOptions {
  frontendDir: string;
  backendDir: string;
  /** Git ref the change is compared against. Without it, the backend contract stored in the index is the baseline. */
  base?: string;
  outDir: string;
  aiProvider?: AiProvider;
  failOn?: ImpactFailOn;
  checkFailOn?: CheckFailOn;
  verifyFailOn?: VerifyFailOn;
  jarPath?: string;
}

export interface CiResult {
  /** 0 = pass, 1 = a check failed at its configured level. */
  exitCode: 0 | 1;
  changes: ChangeReport | VerifiedChangeReport | null;
  /** Why the change analysis was skipped, when it was. */
  changesSkipped: string | null;
  contract: ContractReport;
  files: { report: string; json: string; changes: string | null; contract: string };
}

/**
 * The full pull-request check shared by every runner (CI script, GitHub
 * Action, Gradle/Maven plugins): index the frontend, analyze the backend API
 * change against the frontend, then check the changed frontend files against
 * the new contract.
 */
export async function runCi(workspace: TacetWorkspace, options: CiOptions): Promise<CiResult> {
  const out = resolve(options.outDir);
  mkdirSync(out, { recursive: true });
  await workspace.indexFrontend(options.frontendDir);

  let changes: CiResult["changes"] = null;
  let changesSkipped: string | null = null;
  let changesFail = false;
  if (options.base) {
    changes = options.aiProvider
      ? await workspace.verifyChanges(options.backendDir, { provider: options.aiProvider, base: options.base, jarPath: options.jarPath })
      : await workspace.diffBackend(options.backendDir, { base: options.base, jarPath: options.jarPath });
  } else if (workspace.hasBackendBaseline()) {
    changes = options.aiProvider
      ? await workspace.verifyChanges(options.backendDir, { provider: options.aiProvider, jarPath: options.jarPath })
      : await workspace.analyzeBackend(options.backendDir, { jarPath: options.jarPath });
  } else {
    changesSkipped = "No git base ref and no stored backend contract to compare against; the next run will use this one.";
  }
  if (changes) {
    changesFail = "ai" in changes
      ? failsVerified(changes, options.verifyFailOn ?? "fail")
      : failsImpact(changes, options.failOn ?? "definite");
  }

  await workspace.extractBackend(options.backendDir, { jarPath: options.jarPath });
  const contract = workspace.check(options.base ? { changedSince: options.base } : {});
  const contractFail = failsContract(contract, options.checkFailOn ?? "error");

  const title = options.base ? `Tacet: backend API changes ${options.base}...working tree` : "Tacet: backend API change report";
  const changesMarkdown = changes ? renderChangeReportMarkdown(changes, title) : null;
  const contractMarkdown = renderContractReportMarkdown(contract);
  const files = {
    report: join(out, "report.md"),
    json: join(out, "report.json"),
    changes: changesMarkdown ? join(out, "api-changes.md") : null,
    contract: join(out, "contract.md"),
  };
  if (changesMarkdown && files.changes) writeFileSync(files.changes, changesMarkdown);
  writeFileSync(files.contract, contractMarkdown);
  writeFileSync(
    files.report,
    [changesMarkdown ?? `## Tacet: backend API changes\n\n_${changesSkipped}_`, contractMarkdown, "<sub>Generated by Tacet.</sub>"].join("\n\n") + "\n",
  );
  const exitCode = changesFail || contractFail ? 1 : 0;
  writeFileSync(files.json, JSON.stringify({ exitCode, changes, changesSkipped, contract }, null, 2));
  return { exitCode, changes, changesSkipped, contract, files };
}

function failsImpact(report: ChangeReport, level: ImpactFailOn): boolean {
  const c = report.counts;
  if (level === "definite") return c.DEFINITE > 0;
  if (level === "likely") return c.DEFINITE + c.LIKELY > 0;
  if (level === "possible") return c.DEFINITE + c.LIKELY + c.POSSIBLE > 0;
  return false;
}

function failsVerified(report: VerifiedChangeReport, level: VerifyFailOn): boolean {
  if (level === "fail") return report.result === "FAIL";
  if (level === "warning") return report.result !== "PASS";
  return false;
}

function failsContract(report: ContractReport, level: CheckFailOn): boolean {
  if (level === "error") return report.counts.error > 0;
  if (level === "warning") return report.counts.error + report.counts.warning > 0;
  return false;
}
